services:
  db:
    image: postgres:15
    container_name: b110t-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: b110t_user
      POSTGRES_PASSWORD: b110t_pass
      POSTGRES_DB: b110t_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: b110t-be
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db # <-- service name of postgres container
      DB_PORT: 5432
      DB_USER: b110t_user
      DB_PASS: b110t_pass
      DB_NAME: b110t_db
      JWT_SECRET: super-secret-prod
    depends_on:
      - db

volumes:
  postgres_data:
